<?php
/**
 * Title: Feature Extensions
 * Slug: extensions
 * Categories: feature
 */
?>
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|xxl","bottom":"0"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="padding-top:var(--wp--preset--spacing--xxl);padding-bottom:0"><!-- wp:group {"align":"wide","layout":{"type":"constrained","contentSize":"1080px"}} -->
<div class="wp-block-group alignwide"><!-- wp:heading {"textAlign":"center"} -->
<h2 class="wp-block-heading has-text-align-center">Professional design system for WordPress block themes</h2>
<!-- /wp:heading -->
<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"align":"center"} -->
<p class="aligncenter has-text-align-center aligncenter">Personalize color palettes, gradients, spacing sizes, shadows, typography, and more. Control at the site-level or fine-tune individual blocks. </p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
<!-- wp:group {"align":"wide","style":{"spacing":{"padding":{"top":"var:preset|spacing|lg","bottom":"0","left":"var:preset|spacing|lg","right":"var:preset|spacing|lg"},"margin":{"top":"var:preset|spacing|lg"}},"border":{"radius":"24px"}},"backgroundColor":"neutral-100","layout":{"type":"default"}} -->
<div class="wp-block-group alignwide has-neutral-100-background-color has-background" style="border-radius:24px;margin-top:var(--wp--preset--spacing--lg);padding-top:var(--wp--preset--spacing--lg);padding-right:var(--wp--preset--spacing--lg);padding-bottom:0;padding-left:var(--wp--preset--spacing--lg)"><!-- wp:columns {"style":{"spacing":{"blockGap":{"top":"var:preset|spacing|xl","left":"var:preset|spacing|xl"}}}} -->
<div class="wp-block-columns"><!-- wp:column {"verticalAlignment":"center","width":"50%","style":{"spacing":{"padding":{"bottom":"var:preset|spacing|lg"}}}} -->
<div class="wp-block-column is-vertically-aligned-center" style="padding-bottom:var(--wp--preset--spacing--lg);flex-basis:50%"><!-- wp:heading {"level":3,"style":{"spacing":{"margin":{"top":"0","bottom":"0"}}},"fontSize":"48"} -->
<h3 class="wp-block-heading has-48-font-size" style="margin-top:0;margin-bottom:0">Change the appearance of your site in one click with global style variations</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Every theme comes with pre-defined global style variations for quickly customizing the entire appearance of your site. Choose from a selection of accessible color palettes and gradients that are designed to work in both dark and light mode.</p>
<!-- /wp:paragraph -->
<!-- wp:group {"style":{"spacing":{"padding":{"bottom":"var:preset|spacing|lg"}},"display":{"all":"none"}},"layout":{"type":"flex","flexWrap":"wrap","orientation":"horizontal"}} -->
<div class="wp-block-group" style="padding-bottom:var(--wp--preset--spacing--lg)"><!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|xs","bottom":"var:preset|spacing|xs","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"},"blockGap":"var:preset|spacing|xs"},"border":{"radius":"4px"}},"backgroundColor":"neutral-0","layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between"}} -->
<div class="wp-block-group has-neutral-0-background-color has-background" style="border-radius:4px;padding-top:var(--wp--preset--spacing--xs);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--xs);padding-left:var(--wp--preset--spacing--sm)"><!-- wp:paragraph {"fontSize":"36"} -->
<p class="has-36-font-size">Aa</p>
<!-- /wp:paragraph -->
<!-- wp:group {"style":{"spacing":{"blockGap":"0px"}},"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:image {"style":{"elements":{"link":{"color":{"text":"var:preset|color|neutral-100"}}}},"className":"is-style-icon","textColor":"neutral-100","iconSet":"wordpress","iconName":"circle-filled","iconSize":"1.2em","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 xml:space=\u0022preserve\u0022 viewBox=\u00220 0 2000 2000\u0022 role=\u0022img\u0022 aria-labelledby=\u0022icon-65ddfb7b89e63\u0022 data-icon=\u0022wordpress-circle-filled\u0022 width=\u002224\u0022 height=\u002224\u0022 fill=\u0022currentColor\u0022\u003e\u003ctitle id=\u0022icon-65ddfb7b89e63\u0022\u003eCircle Filled Icon\u003c/title\u003e\u003ccircle cx=\u00221000\u0022 cy=\u00221000\u0022 r=\u0022750\u0022\u003e\u003c/circle\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image is-style-icon has-neutral-100-color has-text-color has-link-color" style="--wp--custom--icon--color:var(--wp--preset--color--neutral-100,currentColor);--wp--custom--icon--size:1.2em;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; xml:space=&quot;preserve&quot; viewBox=&quot;0 0 2000 2000&quot; role=&quot;img&quot; aria-labelledby=&quot;icon-65ddfb7b89e63&quot; data-icon=&quot;wordpress-circle-filled&quot; width=&quot;24&quot; height=&quot;24&quot; fill=&quot;currentColor&quot;&gt;<title id=&quot;icon-65ddfb7b89e63&quot;&gt;Circle Filled Icon</title&gt;<circle cx=&quot;1000&quot; cy=&quot;1000&quot; r=&quot;750&quot;&gt;</circle&gt;</svg&gt;')"><img alt=""/></figure>
<!-- /wp:image -->
<!-- wp:image {"className":"is-style-icon","iconSet":"wordpress","iconName":"circle-filled","iconSize":"1.2em","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 xml:space=\u0022preserve\u0022 viewBox=\u00220 0 2000 2000\u0022 role=\u0022img\u0022 aria-labelledby=\u0022icon-65ddfb7b89e63\u0022 data-icon=\u0022wordpress-circle-filled\u0022 width=\u002224\u0022 height=\u002224\u0022 fill=\u0022currentColor\u0022\u003e\u003ctitle id=\u0022icon-65ddfb7b89e63\u0022\u003eCircle Filled Icon\u003c/title\u003e\u003ccircle cx=\u00221000\u0022 cy=\u00221000\u0022 r=\u0022750\u0022\u003e\u003c/circle\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image is-style-icon" style="--wp--custom--icon--size:1.2em;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; xml:space=&quot;preserve&quot; viewBox=&quot;0 0 2000 2000&quot; role=&quot;img&quot; aria-labelledby=&quot;icon-65ddfb7b89e63&quot; data-icon=&quot;wordpress-circle-filled&quot; width=&quot;24&quot; height=&quot;24&quot; fill=&quot;currentColor&quot;&gt;<title id=&quot;icon-65ddfb7b89e63&quot;&gt;Circle Filled Icon</title&gt;<circle cx=&quot;1000&quot; cy=&quot;1000&quot; r=&quot;750&quot;&gt;</circle&gt;</svg&gt;')"><img alt=""/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|xs","bottom":"var:preset|spacing|xs","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"},"blockGap":"var:preset|spacing|xs"},"border":{"radius":"4px"},"elements":{"link":{"color":{"text":"#4584f7"}}},"color":{"text":"#4584f7"}},"backgroundColor":"neutral-0","layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between"}} -->
<div class="wp-block-group has-neutral-0-background-color has-text-color has-background has-link-color" style="border-radius:4px;color:#4584f7;padding-top:var(--wp--preset--spacing--xs);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--xs);padding-left:var(--wp--preset--spacing--sm)"><!-- wp:paragraph {"fontSize":"36"} -->
<p class="has-36-font-size">Aa</p>
<!-- /wp:paragraph -->
<!-- wp:group {"style":{"spacing":{"blockGap":"0px"}},"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:image {"style":{"elements":{"link":{"color":{"text":"#4584f752"}}},"color":{"text":"#4584f752"}},"className":"is-style-icon","iconSet":"wordpress","iconName":"circle-filled","iconSize":"1.2em","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 xml:space=\u0022preserve\u0022 viewBox=\u00220 0 2000 2000\u0022 role=\u0022img\u0022 aria-labelledby=\u0022icon-65ddfb7b89e63\u0022 data-icon=\u0022wordpress-circle-filled\u0022 width=\u002224\u0022 height=\u002224\u0022 fill=\u0022currentColor\u0022\u003e\u003ctitle id=\u0022icon-65ddfb7b89e63\u0022\u003eCircle Filled Icon\u003c/title\u003e\u003ccircle cx=\u00221000\u0022 cy=\u00221000\u0022 r=\u0022750\u0022\u003e\u003c/circle\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image is-style-icon has-text-color has-link-color" style="color:#4584f752;--wp--custom--icon--color:#4584f752;--wp--custom--icon--size:1.2em;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; xml:space=&quot;preserve&quot; viewBox=&quot;0 0 2000 2000&quot; role=&quot;img&quot; aria-labelledby=&quot;icon-65ddfb7b89e63&quot; data-icon=&quot;wordpress-circle-filled&quot; width=&quot;24&quot; height=&quot;24&quot; fill=&quot;currentColor&quot;&gt;<title id=&quot;icon-65ddfb7b89e63&quot;&gt;Circle Filled Icon</title&gt;<circle cx=&quot;1000&quot; cy=&quot;1000&quot; r=&quot;750&quot;&gt;</circle&gt;</svg&gt;')"><img alt=""/></figure>
<!-- /wp:image -->
<!-- wp:image {"className":"is-style-icon","iconSet":"wordpress","iconName":"circle-filled","iconSize":"1.2em","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 xml:space=\u0022preserve\u0022 viewBox=\u00220 0 2000 2000\u0022 role=\u0022img\u0022 aria-labelledby=\u0022icon-65ddfb7b89e63\u0022 data-icon=\u0022wordpress-circle-filled\u0022 width=\u002224\u0022 height=\u002224\u0022 fill=\u0022currentColor\u0022\u003e\u003ctitle id=\u0022icon-65ddfb7b89e63\u0022\u003eCircle Filled Icon\u003c/title\u003e\u003ccircle cx=\u00221000\u0022 cy=\u00221000\u0022 r=\u0022750\u0022\u003e\u003c/circle\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image is-style-icon" style="--wp--custom--icon--size:1.2em;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; xml:space=&quot;preserve&quot; viewBox=&quot;0 0 2000 2000&quot; role=&quot;img&quot; aria-labelledby=&quot;icon-65ddfb7b89e63&quot; data-icon=&quot;wordpress-circle-filled&quot; width=&quot;24&quot; height=&quot;24&quot; fill=&quot;currentColor&quot;&gt;<title id=&quot;icon-65ddfb7b89e63&quot;&gt;Circle Filled Icon</title&gt;<circle cx=&quot;1000&quot; cy=&quot;1000&quot; r=&quot;750&quot;&gt;</circle&gt;</svg&gt;')"><img alt=""/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|xs","bottom":"var:preset|spacing|xs","left":"var:preset|spacing|sm","right":"var:preset|spacing|sm"},"blockGap":"var:preset|spacing|xs"},"border":{"radius":"4px"},"elements":{"link":{"color":{"text":"#ca80f4"}}},"color":{"text":"#ca80f4"}},"backgroundColor":"neutral-0","layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between"}} -->
<div class="wp-block-group has-neutral-0-background-color has-text-color has-background has-link-color" style="border-radius:4px;color:#ca80f4;padding-top:var(--wp--preset--spacing--xs);padding-right:var(--wp--preset--spacing--sm);padding-bottom:var(--wp--preset--spacing--xs);padding-left:var(--wp--preset--spacing--sm)"><!-- wp:paragraph {"fontSize":"36"} -->
<p class="has-36-font-size">Aa</p>
<!-- /wp:paragraph -->
<!-- wp:group {"style":{"spacing":{"blockGap":"0px"}},"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:image {"style":{"color":{"text":"#ca7ff582"},"elements":{"link":{"color":{"text":"#ca7ff582"}}}},"className":"is-style-icon","iconSet":"wordpress","iconName":"circle-filled","iconSize":"1.2em","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 xml:space=\u0022preserve\u0022 viewBox=\u00220 0 2000 2000\u0022 role=\u0022img\u0022 aria-labelledby=\u0022icon-65ddfb7b89e63\u0022 data-icon=\u0022wordpress-circle-filled\u0022 width=\u002224\u0022 height=\u002224\u0022 fill=\u0022currentColor\u0022\u003e\u003ctitle id=\u0022icon-65ddfb7b89e63\u0022\u003eCircle Filled Icon\u003c/title\u003e\u003ccircle cx=\u00221000\u0022 cy=\u00221000\u0022 r=\u0022750\u0022\u003e\u003c/circle\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image is-style-icon has-text-color has-link-color" style="color:#ca7ff582;--wp--custom--icon--color:#ca7ff582;--wp--custom--icon--size:1.2em;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; xml:space=&quot;preserve&quot; viewBox=&quot;0 0 2000 2000&quot; role=&quot;img&quot; aria-labelledby=&quot;icon-65ddfb7b89e63&quot; data-icon=&quot;wordpress-circle-filled&quot; width=&quot;24&quot; height=&quot;24&quot; fill=&quot;currentColor&quot;&gt;<title id=&quot;icon-65ddfb7b89e63&quot;&gt;Circle Filled Icon</title&gt;<circle cx=&quot;1000&quot; cy=&quot;1000&quot; r=&quot;750&quot;&gt;</circle&gt;</svg&gt;')"><img alt=""/></figure>
<!-- /wp:image -->
<!-- wp:image {"className":"is-style-icon","iconSet":"wordpress","iconName":"circle-filled","iconSize":"1.2em","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 xml:space=\u0022preserve\u0022 viewBox=\u00220 0 2000 2000\u0022 role=\u0022img\u0022 aria-labelledby=\u0022icon-65ddfb7b89e63\u0022 data-icon=\u0022wordpress-circle-filled\u0022 width=\u002224\u0022 height=\u002224\u0022 fill=\u0022currentColor\u0022\u003e\u003ctitle id=\u0022icon-65ddfb7b89e63\u0022\u003eCircle Filled Icon\u003c/title\u003e\u003ccircle cx=\u00221000\u0022 cy=\u00221000\u0022 r=\u0022750\u0022\u003e\u003c/circle\u003e\u003c/svg\u003e"} -->
<figure class="wp-block-image is-style-icon" style="--wp--custom--icon--size:1.2em;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; xml:space=&quot;preserve&quot; viewBox=&quot;0 0 2000 2000&quot; role=&quot;img&quot; aria-labelledby=&quot;icon-65ddfb7b89e63&quot; data-icon=&quot;wordpress-circle-filled&quot; width=&quot;24&quot; height=&quot;24&quot; fill=&quot;currentColor&quot;&gt;<title id=&quot;icon-65ddfb7b89e63&quot;&gt;Circle Filled Icon</title&gt;<circle cx=&quot;1000&quot; cy=&quot;1000&quot; r=&quot;750&quot;&gt;</circle&gt;</svg&gt;')"><img alt=""/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->
<!-- wp:column {"verticalAlignment":"bottom","width":"50%","style":{"border":{"radius":{"bottomLeft":"0px","bottomRight":"0px"}}}} -->
<div class="wp-block-column is-vertically-aligned-bottom" style="border-bottom-left-radius:0px;border-bottom-right-radius:0px;flex-basis:50%"><!-- wp:group {"style":{"display":{"all":"none"}},"layout":{"type":"default","orientation":"horizontal"}} -->
<div class="wp-block-group"><!-- wp:shortcode -->
[blockify_primary_colors]
<!-- /wp:shortcode --></div>
<!-- /wp:group -->
<!-- wp:group {"style":{"position":{"all":"relative"},"spacing":{"padding":{"left":"var:preset|spacing|xl","top":"0"}}},"layout":{"type":"default","orientation":"horizontal"}} -->
<div class="wp-block-group" style="padding-top:0;padding-left:var(--wp--preset--spacing--xl)"><!-- wp:image {"id":2295,"sizeSlug":"full","linkDestination":"none","style":{"aspectRatio":{"all":"5/4"},"objectPosition":{"all":"top"},"border":{"radius":{"bottomLeft":"0px","bottomRight":"0px","topLeft":"12px","topRight":"12px"}},"objectFit":{"all":"cover"},"height":null}} -->
<figure class="wp-block-image size-full has-custom-border" style="border-top-left-radius:12px;border-top-right-radius:12px;border-bottom-left-radius:0px;border-bottom-right-radius:0px"><img src="<?php echo esc_url( home_url() ) ?>/wp-content/uploads/2024/02/Screenshot-2024-02-27-at-11.56.57-pm.png" alt="" class="wp-image-2295" style="border-top-left-radius:12px;border-top-right-radius:12px;border-bottom-left-radius:0px;border-bottom-right-radius:0px"/></figure>
<!-- /wp:image -->
<!-- wp:image {"id":2259,"sizeSlug":"full","linkDestination":"none","style":{"position":{"all":"absolute"},"top":{"all":""},"right":{"all":""},"bottom":{"all":"0px"},"left":{"all":"0px"},"height":null,"width":{"all":"180px"},"border":{"radius":{"topLeft":"4px","topRight":"4px","bottomLeft":"0px","bottomRight":"0px"},"top":{"color":"#03071224","width":"1px"},"right":{"color":"#03071224","width":"1px"},"bottom":{"radius":{"topLeft":"4px","topRight":"4px","bottomLeft":"0px","bottomRight":"0px"},"width":"0px","style":"none"},"left":{"color":"#03071224","width":"1px"}},"aspectRatio":null,"objectPosition":null,"objectFit":null,"maxWidth":{"all":"50%"},"color":{"background":"#fffffe"}}} -->
<figure class="wp-block-image size-full has-custom-border has-background" style="border-top-left-radius:4px;border-top-right-radius:4px;border-bottom-left-radius:0px;border-bottom-right-radius:0px;border-top-color:#03071224;border-top-width:1px;border-right-color:#03071224;border-right-width:1px;border-bottom-style:none;border-bottom-width:0px;border-left-color:#03071224;border-left-width:1px;background-color:#fffffe"><img src="<?php echo esc_url( home_url() ) ?>/wp-content/uploads/2024/02/Screenshot-2024-02-27-at-10.52.27-pm.png" alt="" class="wp-image-2259" style="border-top-left-radius:4px;border-top-right-radius:4px;border-bottom-left-radius:0px;border-bottom-right-radius:0px;border-top-color:#03071224;border-top-width:1px;border-right-color:#03071224;border-right-width:1px;border-bottom-style:none;border-bottom-width:0px;border-left-color:#03071224;border-left-width:1px"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->
<!-- wp:columns {"align":"wide","style":{"spacing":{"margin":{"top":"var:preset|spacing|md"},"blockGap":{"top":"var:preset|spacing|md","left":"var:preset|spacing|md"}}}} -->
<div class="wp-block-columns alignwide" style="margin-top:var(--wp--preset--spacing--md)"><!-- wp:column {"style":{"spacing":{"padding":{"top":"var:preset|spacing|lg","bottom":"0","left":"var:preset|spacing|lg","right":"var:preset|spacing|lg"}}},"backgroundColor":"neutral-100"} -->
<div class="wp-block-column has-neutral-100-background-color has-background" style="padding-top:var(--wp--preset--spacing--lg);padding-right:var(--wp--preset--spacing--lg);padding-bottom:0;padding-left:var(--wp--preset--spacing--lg)"><!-- wp:heading {"level":4} -->
<h4 class="wp-block-heading">Typography Scale</h4>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Font size presets based on the 4pt grid system for consistent vertical rhythm. The typography system utilizes fluid and intrinsic font sizes for automatic responsive scaling.</p>
<!-- /wp:paragraph -->
<!-- wp:group {"style":{"position":{"all":"relative"},"spacing":{"padding":{"left":"var:preset|spacing|lg","top":"var:preset|spacing|sm"}}},"layout":{"type":"default"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--sm);padding-left:var(--wp--preset--spacing--lg)"><!-- wp:image {"id":2274,"sizeSlug":"full","linkDestination":"none","style":{"aspectRatio":{"all":"5/4"},"objectPosition":{"all":"top"},"border":{"radius":{"bottomLeft":"0px","bottomRight":"0px","topLeft":"12px","topRight":"12px"}},"objectFit":{"all":"cover"}}} -->
<figure class="wp-block-image size-full has-custom-border" style="border-top-left-radius:12px;border-top-right-radius:12px;border-bottom-left-radius:0px;border-bottom-right-radius:0px"><img src="<?php echo esc_url( home_url() ) ?>/wp-content/uploads/2024/02/Screenshot-2024-02-27-at-11.25.38-pm.png" alt="" class="wp-image-2274" style="border-top-left-radius:12px;border-top-right-radius:12px;border-bottom-left-radius:0px;border-bottom-right-radius:0px"/></figure>
<!-- /wp:image -->
<!-- wp:image {"id":2260,"sizeSlug":"large","linkDestination":"none","style":{"position":{"all":"absolute"},"top":{"all":""},"right":{"all":""},"bottom":{"all":"0px"},"left":{"all":"0px"},"height":{"all":""},"width":{"all":"30%"},"border":{"radius":{"topLeft":"4px","topRight":"4px","bottomLeft":"0px","bottomRight":"0px"},"top":{"radius":{"topLeft":"4px","topRight":"4px","bottomLeft":"0px","bottomRight":"0px"},"width":"1px","color":"#03071224"},"right":{"radius":{"topLeft":"4px","topRight":"4px","bottomLeft":"0px","bottomRight":"0px"},"width":"1px","color":"#03071224"},"bottom":{"radius":{"topLeft":"4px","topRight":"4px","bottomLeft":"0px","bottomRight":"0px"},"width":"0px","color":"#03071224","style":"none"},"left":{"radius":{"topLeft":"4px","topRight":"4px","bottomLeft":"0px","bottomRight":"0px"},"width":"1px","color":"#03071224"}},"aspectRatio":{"all":"9/16"},"objectPosition":{"all":"top"},"objectFit":{"all":"cover"},"maxWidth":{"all":"150px"}}} -->
<figure class="wp-block-image size-large has-custom-border" style="border-top-left-radius:4px;border-top-right-radius:4px;border-bottom-left-radius:0px;border-bottom-right-radius:0px;border-top-color:#03071224;border-top-width:1px;border-right-color:#03071224;border-right-width:1px;border-bottom-color:#03071224;border-bottom-style:none;border-bottom-width:0px;border-left-color:#03071224;border-left-width:1px"><img src="<?php echo esc_url( home_url() ) ?>/wp-content/uploads/2024/02/Screenshot-2024-02-27-at-10.53.32-pm-524x1024.png" alt="" class="wp-image-2260" style="border-top-left-radius:4px;border-top-right-radius:4px;border-bottom-left-radius:0px;border-bottom-right-radius:0px;border-top-color:#03071224;border-top-width:1px;border-right-color:#03071224;border-right-width:1px;border-bottom-color:#03071224;border-bottom-style:none;border-bottom-width:0px;border-left-color:#03071224;border-left-width:1px"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->
<!-- wp:column {"verticalAlignment":"stretch","style":{"spacing":{"padding":{"top":"var:preset|spacing|lg","bottom":"0","left":"var:preset|spacing|lg","right":"var:preset|spacing|lg"}}},"backgroundColor":"neutral-100"} -->
<div class="wp-block-column is-vertically-aligned-stretch has-neutral-100-background-color has-background" style="padding-top:var(--wp--preset--spacing--lg);padding-right:var(--wp--preset--spacing--lg);padding-bottom:0;padding-left:var(--wp--preset--spacing--lg)"><!-- wp:heading {"level":4} -->
<h4 class="wp-block-heading">Spacing and Grid</h4>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>Margin, padding and block gap presets based on the 4px grid system for consistent spacing and alignment. Additional support for custom grid layouts with responsive settings.</p>
<!-- /wp:paragraph -->
<!-- wp:group {"style":{"position":{"all":"relative"},"spacing":{"padding":{"left":"0","top":"var:preset|spacing|sm","right":"var:preset|spacing|lg"}}},"layout":{"type":"default"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--sm);padding-right:var(--wp--preset--spacing--lg);padding-left:0"><!-- wp:image {"id":2278,"sizeSlug":"full","linkDestination":"none","style":{"aspectRatio":{"all":"5/4"},"objectPosition":{"all":"top"},"border":{"radius":{"bottomLeft":"0px","bottomRight":"0px","topLeft":"12px","topRight":"12px"}},"objectFit":{"all":"cover"}}} -->
<figure class="wp-block-image size-full has-custom-border" style="border-top-left-radius:12px;border-top-right-radius:12px;border-bottom-left-radius:0px;border-bottom-right-radius:0px"><img src="<?php echo esc_url( home_url() ) ?>/wp-content/uploads/2024/02/Screenshot-2024-02-27-at-11.33.05-pm.png" alt="" class="wp-image-2278" style="border-top-left-radius:12px;border-top-right-radius:12px;border-bottom-left-radius:0px;border-bottom-right-radius:0px"/></figure>
<!-- /wp:image -->
<!-- wp:image {"id":2280,"sizeSlug":"full","linkDestination":"none","style":{"position":{"all":"absolute"},"top":{"all":""},"right":{"all":"0px"},"bottom":{"all":"0px"},"left":{"all":""},"height":{"all":""},"width":{"all":"30%"},"border":{"radius":{"topLeft":"4px","topRight":"4px","bottomLeft":"0px","bottomRight":"0px"},"top":{"radius":{"topLeft":"4px","topRight":"4px","bottomLeft":"0px","bottomRight":"0px"},"width":"1px","color":"#03071224"},"right":{"radius":{"topLeft":"4px","topRight":"4px","bottomLeft":"0px","bottomRight":"0px"},"width":"1px","color":"#03071224"},"bottom":{"radius":{"topLeft":"4px","topRight":"4px","bottomLeft":"0px","bottomRight":"0px"},"width":"0px","color":"#03071224","style":"none"},"left":{"radius":{"topLeft":"4px","topRight":"4px","bottomLeft":"0px","bottomRight":"0px"},"width":"1px","color":"#03071224"}},"aspectRatio":{"all":"9/16"},"objectPosition":{"all":"top"},"objectFit":{"all":"cover"},"maxWidth":{"all":"150px"}}} -->
<figure class="wp-block-image size-full has-custom-border" style="border-top-left-radius:4px;border-top-right-radius:4px;border-bottom-left-radius:0px;border-bottom-right-radius:0px;border-top-color:#03071224;border-top-width:1px;border-right-color:#03071224;border-right-width:1px;border-bottom-color:#03071224;border-bottom-style:none;border-bottom-width:0px;border-left-color:#03071224;border-left-width:1px"><img src="<?php echo esc_url( home_url() ) ?>/wp-content/uploads/2024/02/Screenshot-2024-02-27-at-11.34.45-pm.png" alt="" class="wp-image-2280" style="border-top-left-radius:4px;border-top-right-radius:4px;border-bottom-left-radius:0px;border-bottom-right-radius:0px;border-top-color:#03071224;border-top-width:1px;border-right-color:#03071224;border-right-width:1px;border-bottom-color:#03071224;border-bottom-style:none;border-bottom-width:0px;border-left-color:#03071224;border-left-width:1px"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->