<?php
/**
 * Title: Feature Themes
 * Slug: themes
 * Categories: feature
 */
?>
<!-- wp:group {"align":"full","style":{"spacing":{"margin":{"top":"0","bottom":"0"},"padding":{"bottom":"var:preset|spacing|xl","top":"0"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull" style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:var(--wp--preset--spacing--xl)"><!-- wp:group {"align":"wide","style":{"spacing":{"margin":{"top":"0","bottom":"0"},"padding":{"top":"0"}}},"layout":{"type":"default"}} -->
<div class="wp-block-group alignwide" style="margin-top:0;margin-bottom:0;padding-top:0"><!-- wp:heading {"textAlign":"center","level":1,"style":{"spacing":{"padding":{"top":"var:preset|spacing|xl","bottom":"var:preset|spacing|xxs"},"margin":{"top":"0","bottom":"0"}},"maxWidth":{"all":"1260px"}},"gradient":"primary-foreground","className":"margin-auto"} -->
<h1 class="wp-block-heading has-text-align-center margin-auto has-primary-foreground-gradient-background has-background" style="margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--xl);padding-bottom:var(--wp--preset--spacing--xxs)">Responsive block themes for the site editor</h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"align":"center","className":"is-style-sub-heading"} -->
<p class="aligncenter has-text-align-center is-style-sub-heading aligncenter">Explore our collection of business, SaaS, startup and agency block themes you can customize with the WordPress code-free site editor.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:group {"align":"wide","style":{"spacing":{"padding":{"top":"var:preset|spacing|lg","bottom":"var:preset|spacing|lg"}}},"layout":{"type":"default"}} -->
<div class="wp-block-group alignwide" style="padding-top:var(--wp--preset--spacing--lg);padding-bottom:var(--wp--preset--spacing--lg)"><!-- wp:query {"queryId":0,"query":{"perPage":"6","pages":0,"offset":0,"postType":"theme","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false,"parents":[]},"align":"wide","layout":{"type":"default"},"style":{"spacing":{"blockGap":"1.5em"}}} -->
<div class="wp-block-query alignwide"><!-- wp:post-template {"style":{"spacing":{"blockGap":"var:preset|spacing|md"}},"layout":{"type":"grid","columnCount":2}} -->
<!-- wp:group {"style":{"spacing":{"blockGap":"0","padding":{"bottom":"var:preset|spacing|xs"}}},"className":"is-style-default","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-default" style="padding-bottom:var(--wp--preset--spacing--xs)"><!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|lg","left":"var:preset|spacing|lg","right":"var:preset|spacing|lg"}},"border":{"radius":"30px"},"overflow":{"all":"hidden"}},"backgroundColor":"neutral-100","layout":{"type":"default"}} -->
<div class="wp-block-group has-neutral-100-background-color has-background" style="border-radius:30px;padding-top:var(--wp--preset--spacing--lg);padding-right:var(--wp--preset--spacing--lg);padding-left:var(--wp--preset--spacing--lg)"><!-- wp:group {"style":{"overflow":{"all":"hidden"},"border":{"radius":{"topLeft":"10px","topRight":"10px"}}},"layout":{"type":"default"}} -->
<div class="wp-block-group" style="border-top-left-radius:10px;border-top-right-radius:10px"><!-- wp:post-featured-image {"isLink":true,"aspectRatio":"auto","style":{"objectPosition":{"all":"top"},"aspectRatio":{"all":"1/1"},"border":{"radius":{"topLeft":"10px","topRight":"10px","bottomLeft":"0px","bottomRight":"0px"}},"objectFit":{"all":"cover"},"width":{"all":"100%"},"height":null,"spacing":{"margin":{"top":"0","bottom":"0"}},"boxShadow":{"color":"var(\u002d\u002dwp\u002d\u002dpreset\u002d\u002dcolor\u002d\u002dtransparent)"},"textShadow":"","transformHover":{"scale":"1.1"}},"shadowPreset":"","shadowPresetHover":"","useCustomBoxShadow":true,"backgroundColor":"neutral-200"} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|md"}}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between","verticalAlignment":"center"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--md)"><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xxs"}},"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:post-title {"level":3,"isLink":true,"style":{"typography":{"lineHeight":"1"}},"fontSize":"24"} /-->
<!-- wp:paragraph -->
<p>Free</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"neutral-100","textColor":"neutral-700","style":{"elements":{"link":{"color":{"text":"var:preset|color|neutral-700"}}},"border":{"width":"1px"}},"borderColor":"neutral-100","className":"is-style-fill","size":"small","iconSet":"heroicons","iconName":"eye","iconSize":"20px","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 fill=\u0022none\u0022 stroke=\u0022currentColor\u0022 stroke-width=\u00221.5\u0022 aria-hidden=\u0022true\u0022 viewBox=\u00220 0 24 24\u0022 role=\u0022img\u0022 aria-labelledby=\u0022icon-65e5cd96334d2\u0022 data-icon=\u0022heroicons-eye\u0022 width=\u002224\u0022 height=\u002224\u0022\u003e\u003ctitle id=\u0022icon-65e5cd96334d2\u0022\u003eEye Icon\u003c/title\u003e\u003cpath stroke-linecap=\u0022round\u0022 stroke-linejoin=\u0022round\u0022 d=\u0022M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z\u0022\u003e\u003c/path\u003e\u003cpath stroke-linecap=\u0022round\u0022 stroke-linejoin=\u0022round\u0022 d=\u0022M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0z\u0022\u003e\u003c/path\u003e\u003c/svg\u003e"} -->
<div class="wp-block-button is-style-fill has-border-color has-neutral-100-border-color" style="border-width:1px;--wp--custom--icon--background:var(--wp--preset--color--neutral-100, currentColor);--wp--custom--icon--color:var(--wp--preset--color--neutral-700,currentColor);--wp--custom--icon--border-width:1px;--wp--custom--icon--border-style:solid;--wp--custom--icon--border-color:var(--wp--preset--color--neutral-100);--wp--custom--icon--size:20px;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; fill=&quot;none&quot; stroke=&quot;currentColor&quot; stroke-width=&quot;1.5&quot; aria-hidden=&quot;true&quot; viewBox=&quot;0 0 24 24&quot; role=&quot;img&quot; aria-labelledby=&quot;icon-65e5cd96334d2&quot; data-icon=&quot;heroicons-eye&quot; width=&quot;24&quot; height=&quot;24&quot;&gt;<title id=&quot;icon-65e5cd96334d2&quot;&gt;Eye Icon</title&gt;<path stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot; d=&quot;M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z&quot;&gt;</path&gt;<path stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot; d=&quot;M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0z&quot;&gt;</path&gt;</svg&gt;')"><a class="wp-block-button__link has-neutral-700-color has-neutral-100-background-color has-text-color has-background has-link-color has-border-color has-neutral-100-border-color wp-element-button" href="https://demo.blockifywp.com/{post_name}" style="border-width:1px" target="_blank" rel="noreferrer noopener">Preview</a></div>
<!-- /wp:button -->
<!-- wp:button {"textColor":"neutral-950","style":{"elements":{"link":{"color":{"text":"var:preset|color|neutral-950"}}}},"className":"is-style-outline","size":"small","iconSet":"heroicons","iconName":"arrow-right","iconSize":"20px","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 fill=\u0022none\u0022 stroke=\u0022currentColor\u0022 stroke-width=\u00221.5\u0022 aria-hidden=\u0022true\u0022 viewBox=\u00220 0 24 24\u0022 role=\u0022img\u0022 aria-labelledby=\u0022icon-65da9dfb62411\u0022 data-icon=\u0022heroicons-arrow-right\u0022 width=\u002224\u0022 height=\u002224\u0022\u003e\u003ctitle id=\u0022icon-65da9dfb62411\u0022\u003eArrow Right Icon\u003c/title\u003e\u003cpath stroke-linecap=\u0022round\u0022 stroke-linejoin=\u0022round\u0022 d=\u0022M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3\u0022\u003e\u003c/path\u003e\u003c/svg\u003e"} -->
<div class="wp-block-button is-style-outline" style="--wp--custom--icon--color:var(--wp--preset--color--neutral-950,currentColor);--wp--custom--icon--size:20px;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; fill=&quot;none&quot; stroke=&quot;currentColor&quot; stroke-width=&quot;1.5&quot; aria-hidden=&quot;true&quot; viewBox=&quot;0 0 24 24&quot; role=&quot;img&quot; aria-labelledby=&quot;icon-65da9dfb62411&quot; data-icon=&quot;heroicons-arrow-right&quot; width=&quot;24&quot; height=&quot;24&quot;&gt;<title id=&quot;icon-65da9dfb62411&quot;&gt;Arrow Right Icon</title&gt;<path stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot; d=&quot;M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3&quot;&gt;</path&gt;</svg&gt;')"><a class="wp-block-button__link has-neutral-950-color has-text-color has-link-color wp-element-button">Learn More</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
<!-- /wp:post-template --></div>
<!-- /wp:query --></div>
<!-- /wp:group -->
<!-- wp:group {"align":"wide","style":{"spacing":{"padding":{"top":"0","bottom":"var:preset|spacing|lg"},"margin":{"top":"0","bottom":"0"}}},"layout":{"type":"default"}} -->
<div class="wp-block-group alignwide" style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:var(--wp--preset--spacing--lg)"><!-- wp:query {"queryId":0,"query":{"perPage":"1","pages":0,"offset":"6","postType":"theme","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false,"parents":[]},"align":"wide","layout":{"type":"default"},"style":{"spacing":{"blockGap":"1.5em"}}} -->
<div class="wp-block-query alignwide"><!-- wp:post-template {"style":{"spacing":{"blockGap":"var:preset|spacing|md"}},"layout":{"type":"grid","columnCount":1}} -->
<!-- wp:group {"style":{"spacing":{"blockGap":"0","padding":{"bottom":"var:preset|spacing|xs"}}},"className":"is-style-default","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-default" style="padding-bottom:var(--wp--preset--spacing--xs)"><!-- wp:columns {"verticalAlignment":"bottom","style":{"spacing":{"padding":{"bottom":"0","top":"var:preset|spacing|xl","right":"var:preset|spacing|xl","left":"var:preset|spacing|xl"},"blockGap":{"top":"var:preset|spacing|xl","left":"var:preset|spacing|xl"}},"border":{"radius":"30px"}},"backgroundColor":"neutral-100"} -->
<div class="wp-block-columns are-vertically-aligned-bottom has-neutral-100-background-color has-background" style="border-radius:30px;padding-top:var(--wp--preset--spacing--xl);padding-right:var(--wp--preset--spacing--xl);padding-bottom:0;padding-left:var(--wp--preset--spacing--xl)"><!-- wp:column {"verticalAlignment":"bottom"} -->
<div class="wp-block-column is-vertically-aligned-bottom"><!-- wp:heading {"level":3,"style":{"typography":{"lineHeight":"1.1"}},"fontSize":"52"} -->
<h3 class="wp-block-heading has-52-font-size" style="line-height:1.1">Blockify framework parent theme</h3>
<!-- /wp:heading -->
<!-- wp:paragraph -->
<p>{post_excerpt}</p>
<!-- /wp:paragraph -->
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|xxs","bottom":"var:preset|spacing|xl"}}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between","verticalAlignment":"center"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--xxs);padding-bottom:var(--wp--preset--spacing--xl)"><!-- wp:buttons {"style":{"spacing":{"blockGap":"var:preset|spacing|sm"}}} -->
<div class="wp-block-buttons"><!-- wp:button {"style":{"spacing":{"padding":{"right":"var:preset|spacing|md","left":"var:preset|spacing|md","top":"var:preset|spacing|xs","bottom":"var:preset|spacing|xs"}}},"fontSize":"16","size":"medium","iconSet":"wordpress","iconName":"arrow-right","iconSize":"22px","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 viewBox=\u00220 0 24 24\u0022 role=\u0022img\u0022 aria-labelledby=\u0022icon-65e546dbd46e7\u0022 data-icon=\u0022wordpress-arrow-right\u0022 width=\u002224\u0022 height=\u002224\u0022 fill=\u0022currentColor\u0022\u003e\u003ctitle id=\u0022icon-65e546dbd46e7\u0022\u003eArrow Right Icon\u003c/title\u003e\u003cpath d=\u0022m14.5 6.5-1 1 3.7 3.7H4v1.6h13.2l-3.7 3.7 1 1 5.6-5.5z\u0022\u003e\u003c/path\u003e\u003c/svg\u003e"} -->
<div class="wp-block-button has-custom-font-size has-16-font-size" style="padding-top:var(--wp--preset--spacing--xs);padding-right:var(--wp--preset--spacing--md);padding-bottom:var(--wp--preset--spacing--xs);padding-left:var(--wp--preset--spacing--md)"><a class="wp-block-button__link wp-element-button" href="http://{permalink}" style="padding-top:var(--wp--preset--spacing--xs);padding-right:var(--wp--preset--spacing--md);padding-bottom:var(--wp--preset--spacing--xs);padding-left:var(--wp--preset--spacing--md)">Learn More</a></div>
<!-- /wp:button -->
<!-- wp:button {"textColor":"neutral-950","style":{"elements":{"link":{"color":{"text":"var:preset|color|neutral-950"}}},"spacing":{"padding":{"right":"var:preset|spacing|md","left":"var:preset|spacing|md","top":"var:preset|spacing|xs","bottom":"var:preset|spacing|xs"}}},"className":"is-style-outline","fontSize":"16","size":"medium","iconSet":"wordpress","iconName":"external","iconSize":"22px","iconSvgString":"\u003csvg xmlns=\u0022http://www.w3.org/2000/svg\u0022 viewBox=\u00220 0 24 24\u0022 role=\u0022img\u0022 aria-labelledby=\u0022icon-65e546dbd80a7\u0022 data-icon=\u0022wordpress-external\u0022 width=\u002224\u0022 height=\u002224\u0022 fill=\u0022currentColor\u0022\u003e\u003ctitle id=\u0022icon-65e546dbd80a7\u0022\u003eExternal Icon\u003c/title\u003e\u003cpath d=\u0022M19.5 4.5h-7V6h4.44l-5.97 5.97 1.06 1.06L18 7.06v4.44h1.5v-7Zm-13 1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-3H17v3a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h3V5.5h-3Z\u0022\u003e\u003c/path\u003e\u003c/svg\u003e"} -->
<div class="wp-block-button has-custom-font-size is-style-outline has-16-font-size" style="padding-top:var(--wp--preset--spacing--xs);padding-right:var(--wp--preset--spacing--md);padding-bottom:var(--wp--preset--spacing--xs);padding-left:var(--wp--preset--spacing--md);--wp--custom--icon--color:var(--wp--preset--color--neutral-950,currentColor);--wp--custom--icon--padding:var(--wp--preset--spacing--xs) var(--wp--preset--spacing--md) var(--wp--preset--spacing--xs) var(--wp--preset--spacing--md);--wp--custom--icon--size:22px;--wp--custom--icon--url:url('data:image/svg+xml;utf8,<svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot; role=&quot;img&quot; aria-labelledby=&quot;icon-65e546dbd80a7&quot; data-icon=&quot;wordpress-external&quot; width=&quot;24&quot; height=&quot;24&quot; fill=&quot;currentColor&quot;&gt;<title id=&quot;icon-65e546dbd80a7&quot;&gt;External Icon</title&gt;<path d=&quot;M19.5 4.5h-7V6h4.44l-5.97 5.97 1.06 1.06L18 7.06v4.44h1.5v-7Zm-13 1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-3H17v3a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h3V5.5h-3Z&quot;&gt;</path&gt;</svg&gt;')"><a class="wp-block-button__link has-neutral-950-color has-text-color has-link-color wp-element-button" href="https://demo.blockifywp.com/{post_name}" style="padding-top:var(--wp--preset--spacing--xs);padding-right:var(--wp--preset--spacing--md);padding-bottom:var(--wp--preset--spacing--xs);padding-left:var(--wp--preset--spacing--md)" target="_blank" rel="noreferrer noopener">View Demo</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->
<!-- wp:column {"verticalAlignment":"bottom","style":{"border":{"radius":"0px"}}} -->
<div class="wp-block-column is-vertically-aligned-bottom" style="border-radius:0px"><!-- wp:post-featured-image {"isLink":true,"aspectRatio":"auto","style":{"objectPosition":{"all":"top"},"aspectRatio":{"all":"1/1"},"border":{"radius":{"topLeft":"20px","topRight":"20px","bottomLeft":"0px","bottomRight":"0px"}},"objectFit":{"all":"cover"},"width":{"all":"100%"},"height":null,"spacing":{"margin":{"top":"0","bottom":"0"}},"boxShadow":{"color":"var(\u002d\u002dwp\u002d\u002dpreset\u002d\u002dcolor\u002d\u002dtransparent)"},"textShadow":""},"shadowPreset":"","shadowPresetHover":"","useCustomBoxShadow":true,"backgroundColor":"neutral-200"} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->
<!-- /wp:post-template --></div>
<!-- /wp:query --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->